import 'package:flutter/material.dart';
import 'package:http/http.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

import 'package:shared_preferences/shared_preferences.dart';

int mobile;
String fatherName;
List<String> stateList = [
  "rajsthan",
  "gujrat",
  "assam",
  "bihar",
  "goa",
  "haryana",
  "himachal",
  "jammu",
  "karnataka",
  "kerala",
  "mp",
  "maharashtra",
  "manipur",
  "meghalaya",
  "mizoram",
  "nagaland",
  "orissa",
  "up",
  "Uk",
  "punjab",
  "sikkim",
  "tamilnadu",
  "tripura",
  "wb",
  "chhattishgarh",
  "jharkhand",
  "telangana",
  "delhi",
  "andaman",
  "dadra",
  "daman",
  "pudu",
  "ladakh"
];
List<String> rajsthan = [
  "Ajmer",
  "Alwar",
  "Banswara",
  "Baran",
  "Badmer",
  "Bharatpur",
  "Bhilwara",
  "Bikaner",
  "Bundi",
  "Chittorgarh",
  "Churu",
  "Dausa",
  "Dhaulpur",
  "Dungarpur",
  "Hanumangarh",
  "Jaipur",
  "Jaisalmer",
  "Jalore",
  "Jhalawar",
  "Jhunjhunu",
  "Jodhpur",
  "Karauli",
  "Kota",
  "Nagau",
  "Pali",
  "Pratapgarh ",
  "Rajsamand",
  "Sawai Madhopur",
  "Sikar",
  "Sirohi",
  "Sri Ganganagar",
  "Tonk",
  "Udaipur"
];
List<String> gujrat = ["ahemdabad", "surat"];
List<String> assam = [
  "Tinsukia",
  "Dibrugarh",
  "Dhemaji",
  "Charadev",
  "Shivsagar",
  "Lakhimpur",
  "Majuli",
  "Jorhat",
  "Bishwanath",
  "Golghat",
  "Karganj Anglong East",
  "Sonitpur",
  "Nagaon",
  "Hojai",
  "Karbi Anglong West",
  "Dima Hasao",
  "Cachar",
  "Halakandi",
  "Karimganj",
  "Morigaon",
  "Udalguri",
  "Darang",
  "Kamrup Mahanagar",
  "Baksa",
  "Nalbari",
  "Kamrup",
  "Barpeta",
  "Chirang",
  "Bongaigaon",
  "Golpara",
  "Kokrajhar",
  "Dhubri",
  " South Salara-Mankachar "
];
List<String> bihar = [
  "Arwal",
  "Aurangabad",
  "Banka",
  "Begusarai",
  "Bhagalpur",
  "Bhojpur",
  "Buxar",
  "Darbhanga",
  "Eastern",
  "Champaran",
  "Gaya",
  "Gopalganj",
  "Jamui",
  "Jehanabad",
  "Katihar",
  "Khagaria",
  "Kishanganj",
  "Lakhisarai",
  "Madhepura",
  "Madhubani",
  "Munger",
  "Muzaffarpur",
  "Nalanda",
  "Nawada",
  "Patna",
  "Completions",
  "Saharsa",
  "Samastipur",
  "Saran",
  "Rohtas",
  "Sheikhpura",
  "Shivahar",
  "Sitamarhi",
  "Supaul",
  "Vaishali",
  "Western",
  "Champaran"
];
List<String> goa = [
  "Chapora",
  "Dabolim",
  "Madgaon",
  "Marmugao (Marmagao)",
  "Panaji Port",
  "Panjim",
  "Pellet Plant Jetty / Shiroda",
  "Talpona"
];
List<String> haryana = [
  "Ambala",
  "Bhiwani",
  "Faridabad",
  "Fatehabad",
  "Gurgaon",
  "Hisar",
  "Jhajjar",
  "Jind",
  "Kaithal",
  "Karnal",
  "Kurukshetra",
  "Mahendragarh",
  "Noonh",
  "Palwal",
  "Panchkula",
  "Panipat",
  "Rewari",
  "Rohtak",
  "Sirsa",
  "Sonipat",
  "Yamunanagar",
  "Charkhidadari"
];
List<String> himachal = [
  "Chamba",
  "Kangra",
  "Lahaul and Spiti",
  "Kullu",
  "Mandi",
  "Hamirpur",
  "Una",
  "Bilaspur",
  "Solan",
  "Sirmaur",
  "Shimla",
  "Kinnaur"
];
List<String> jammu = [
  "Jammu",
  "Doda",
  "Kishtwar",
  "Rajouri",
  "Reasi",
  "Udhampur",
  "Ramban",
  "Kathua",
  "Samba",
  "Poonch",
  "Srinagar",
  "Anantnag",
  "Kulgam ",
  "Pulwama",
  "Shopian",
  "Budgam",
  "Ganderbal",
  "Bandipora",
  "Baramula",
  "Kupwara"
];
List<String> karnataka = [
  "Bagalkot",
  "Bangalore",
  "Bangalore Rural",
  "Belgaum",
  "Bellary",
  "Bidar",
  "Vijayapura",
  "Chamarajanagar",
  "Chikballapur",
  "Chikmagalur",
  "Chitradurga",
  "Dakshina Kannada",
  "Davangere",
  "Dharwad",
  "Gadag",
  "Gulbarga",
  "Hassan",
  "Haveri",
  "Kodagu",
  "Kolar",
  "Koppal",
  "Mandya",
  "Mysore",
  " Raichur ",
  "Ramnagar",
  "Shimoga",
  "Tumkur",
  "Udupi",
  "Uttara Kannada",
  "Yadgir",
  "Vadodara",
  "Valsad"
];
List<String> kerala = [
  "Kalpetta",
  "Idukki",
  "Pathanamthitta",
  "Kasaragod",
  "Kottayam",
  "Alappuzha",
  "Kannur",
  "Kollam",
  "Palakkad",
  "Kozhikode",
  "Thrissur",
  "Ernakulam",
  "Thiruvananthapuram",
  " Mallapuram "
];
List<String> mp = [
  "Jabalpur",
  "Katni",
  "Bhopal",
  "Sidhi",
  "Barwani",
  "Gwalior",
  "Dhar",
  "Ujjain",
  "Harda",
  "Shivpuri",
  "Mandsaur",
  "Raisen",
  "Shajapur ",
  "Vidisha",
  "Sheopur",
  "Ashok Nagar",
  "Satna",
  "Guna",
  "Khandwa (East Nimar)",
  "Dindori",
  "Hoshangabad",
  "Singroli",
  "Umaria",
  "Ratlam",
  " Rajgarh ",
  "Dewas",
  "Chhatarpur",
  "Alirajpur",
  "Burhanpur",
  "Bhind",
  "Sagar",
  "Neemuch",
  "Datia",
  "Panna",
  "Sihor",
  "Khargone (West Nimar)",
  "Rewa ",
  "Seoni",
  "Shahdol",
  "Damoh",
  "Tikamgarh",
  "Jhabua",
  "Indore",
  "Morena",
  "Narsinghpur",
  "Balaghat",
  "Mandla",
  "Chhindwara",
  "Betul",
  "Anuppur ",
  " Agar ",
  " Niwari District "
];
List<String> maharashtra = [
  "Ahmednagar",
  "Akola",
  "Amravati",
  "Aurangabad",
  "Beed",
  "Bhandara",
  "Buldhana",
  "Chandrapur",
  "Dhule",
  "Gadchirouli",
  "Gondia",
  "Hingoli",
  "Jalgaon.",
  "Jalna",
  "Kolhapur",
  "Latur",
  "Mumbai city",
  "Mumbai suburb",
  "Nagpur",
  "Nanded",
  "Nandurbar",
  "Nasik",
  "Osmanabad",
  "Parbhani",
  "Palghar",
  "Pune",
  "Raigarh",
  "Ratnagiri",
  "Sangli",
  "Satara",
  "Sindhudurg",
  "Solapur",
  "Thane",
  "Wardha",
  "Washim",
  "Yavatmal"
];
List<String> manipur = [
  "Bishnupur",
  "Churchandpur",
  "Chandel",
  "Imphal East",
  "Senapati",
  "Tamenglong",
  "Thobal",
  "Ukhrul",
  "Imphal West",
  "Kakking",
  "Jiribam",
  "Kamkong",
  "Noni",
  "Feraljol",
  "Tanganupal",
  "Kangpokpi"
];
List<String> meghalaya = [
  "East Khasi Hills",
  "South Garo Hills",
  "West Jaintia Hills",
  "West Khasi Hills",
  "East Garo Hills",
  "Ri Bhoi",
  "South West Khasi Hills",
  "East Jaintia Hills",
  "North Garo Hills",
  "Southwest Garo Hills",
  "West Garo Hills"
];
List<String> mizoram = [
  "Aizawl",
  "Kolasib",
  "Longalai",
  "Lunglei",
  "Mamit",
  "Saiha",
  "Serchhip",
  "Champhai"
];
List<String> nagaland = [
  "Longleng",
  "Kohima",
  "Mon",
  "Tuensang",
  "Mokokchung",
  "Wokha",
  "Phek",
  "Junheboto",
  "Peren",
  "Kafair",
  "Dimapur"
];
List<String> orissa = [
  "Angul",
  "Balangir",
  "Balasore",
  "Bargarh District",
  "Buddhist District",
  "Bhadrak",
  "Cuttack",
  "Devgarh",
  "Dhenkanal",
  "Gajapati",
  "Ganjam",
  "Jagatsinghpur",
  "Jajpur",
  "Jharsuguda",
  "Kalahandi",
  "Kandhamal",
  "Kendrapara",
  "Kendujhar (Keonjhar)",
  "Khoradha",
  "Koraput",
  "Malkangiri",
  "Mayurbhanj",
  "Nabarangpur",
  "Nayagarh",
  "Nuapada",
  "Puri",
  "Rayagada",
  "Sambalpur",
  "Subarnapur (Sonepur)",
  "Sundargarh"
];
List<String> up = [
  "Agra",
  "Allahabad",
  "Aligarh Uttar Pradesh",
  "Amethi",
  "Auraiya",
  "Azamgarh",
  "Barabanki Uttar Pradesh",
  "Baghpat",
  "Badaun",
  "Bahraich Uttar Pradesh",
  "Bijnor",
  "Ballia Uttar Pradesh",
  "Banda Uttar Pradesh",
  "Balrampur Uttar Pradesh",
  "Bareilly",
  "Basti Uttar Pradesh",
  "Bulandshahar",
  "Chandauli",
  "Chitrakoot",
  "Deoria",
  "Etah Uttar Pradesh",
  "Etawah",
  "Firozabad",
  "Farrukhabad",
  "Fatehpur",
  "Faizabad",
  "Gautam Buddha Nagar",
  "Gonda",
  "Ghazipur",
  "Gorakhpur",
  "Ghaziabad",
  "Hapur ",
  "Hamirpur",
  "Hardoi",
  "Hathras",
  "Jhansi",
  "Amroha",
  "Jaunpur",
  "Ambedkar Nagar",
  "Kannauj",
  "Kanpur",
  "Kanpur Dehat",
  "Kasganj",
  "Kaushambi",
  "Kushinagar",
  "Lalitpur",
  "Lakhimpur Kheri",
  "Lucknow",
  "Mau",
  "Meerut",
  "Maharajganj",
  "Mahoba",
  "Mirzapur",
  "Moradabad",
  "Mainpuri",
  "Mathura",
  "Muzaffarnagar",
  " Pilibhit ",
  "Pratapgarh",
  "Rampur",
  "Rae Bareli",
  "Saharanpur",
  "Sitapur",
  "Shahjahanpur",
  "Shamli",
  "Sambhal",
  "Siddharthanagar",
  "Sonbhadra",
  "Bhadohi",
  "Sultanpur",
  "Shravasti",
  " Unnao ",
  "Varanasi",
  "Sant Kabir Nagar",
  "Jalaun"
];
List<String> uk = [
  "Almora",
  "Bageshwar",
  "Chamoli",
  "Champawat",
  "Dehradun",
  "Haridwar",
  "Nainital",
  "Pauri Garhwal",
  "Pithoragarh",
  "Rudraprayag",
  "Tehri Garhwal",
  "Udham Singh Nagar ",
  " Uttarkashi "
];
List<String> punjab = [
  "Ludhiana",
  "Amritsar",
  "Jalandhar",
  "Sahibzada Ajit Singh Nagar",
  "Gurdaspur",
  "Patiala",
  "Fatehgarh Sahib",
  "Kapurthala",
  "Rupnagar",
  "Shaheed Bhagat Singh Nagar",
  "Hoshiarpur",
  "Tarn Taran",
  "Sangrur",
  "Moga",
  "Faridkot",
  "Barnala",
  "Bathinda",
  "Firozpur",
  "Mansa",
  "Muktsar",
  "Pathankot",
  "Fazilka"
];
List<String> sikkim = [
  "East Sikkim",
  "North Sikkim",
  "South Sikkim",
  "West Sikkim"
];
List<String> tamilnadu = [
  "Ariyalur",
  "Chennai",
  "Coimbatore",
  "Cuddalore",
  "Dharmapuri",
  "Dindigul",
  "Erode",
  "Kanchipuram",
  "Kanyakumari",
  "Karur",
  "Krishnagiri",
  "Madurai",
  "Nagapattanam",
  "Namakkal",
  "Perambalur",
  "Pudukkottai",
  "Ramanathapuram",
  "Salem",
  "Sivaganga",
  "Thanjavur",
  "Nilgiri",
  "Theni",
  "Thiruvallur",
  "Thiruvarur",
  "Thoothukkudi",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupur",
  "Tiruvannamalai",
  "Vellore",
  "Vellore",
  "Virudhunagar"
];
List<String> tripura = [
  "Dhalai",
  "North Tripura",
  "South Tripura",
  "West Tripura",
  "Khowai",
  "Sipahijala",
  "Gomti",
  "Unakoti"
];
List<String> westbengal = [
  "Dakshin Dinajpur",
  "Purulia",
  "South 24 Parganas",
  "North 24 Parganas",
  "Nadia",
  "Murshidabad",
  "Purba Medinipur",
  "West Medinipur",
  "Malda",
  "Kolkata",
  "Cooch Behar",
  "Jalpaiguri",
  "Howrah",
  "Hooghly",
  "Uttar Dinajpur",
  "Darjeeling",
  "Bardhaman",
  "Bankura",
  "Birbhum",
  "Alipurduar",
  "Jhargram"
];
List<String> chhattisgarh = [
  "Balod",
  "Baloda Bazar",
  "Balrampur-Ramanujganj",
  "Bastar",
  "Bemetra",
  "Bijapur",
  "Bilaspur",
  "Dantewada",
  "Dhamtari",
  "Durg",
  "Gariaband",
  "Janjgir-Champa",
  "Jashpur",
  "Kawardha",
  "Kanker",
  "Kondagaon",
  "Korba",
  "Korea",
  "Mahasamund",
  "Mungeli",
  "Narayanpur",
];
List<String> jharkhand = [
  "Ranchi",
  "Dhanbad",
  "Giridih",
  "East Singhbhum",
  "Bokaro",
  "Palamu",
  "Hazaribagh",
  "West Singhbhum",
  "Deoghar",
  "Garhwa",
  "Dumka",
  "Godda",
  "Sahibganj",
  "Saraikela Kharsawan",
  "Chatra",
  "Gumla",
  "Ramgarh",
  "Pakur",
  "Jamtara",
  "Latehar",
  "Koderma",
  "Simdega",
  "Khunti",
  " Lohardaga "
];
List<String> telangana = [
  "Adilabad",
  "Komaram Bhima",
  "Bhadradri Kothagudam",
  "Jaishankar Bhuppal",
  "Jogulba Gadwal",
  "Hyderabad",
  "Jagtial",
  "Jangaon",
  "Kamareddy",
  "Karimnagar",
  "Khammam",
  "Mahbubabad",
  "Mahbubnagar",
  "Mancherial",
  "Medak",
  "Medchal Malkajgiri",
  "Nalgonda",
  "Nagarkurnool",
  "Nirmal",
  "Nizamabad",
  "Rangareddy",
  "Peddapalli",
  "Rajanna Sircilla",
  "Sangareddy",
  "Siddipet",
  "Suryapet",
  "Vikarabad",
  "Vanaparthi",
  "Warangal City",
  "Warangal (Rural)",
  "Yadadri Bhuvanagiri",
  "Narayanpet",
  "Sammakka Mulugu"
];
List<String> delhi = [
  "Daryaganj",
  "Sadarbazar",
  "Saket",
  "Preetvihar",
  "Shahdara",
  "Palam,",
  "Rajaurigardan",
  "Kanatapales",
  "Kanjhawala"
];
List<String> andaman = [
  "South Andaman",
  "North and Central Andaman",
  "Nicobar"
];
List<String> dadra = ["Dadra and Nagar Haveli", "Silvassa"];
List<String> daman = [
  "Daman and Diu",
  "Lakshadweep - Kavretti",
];
List<String> pudu = ["Karaikal", "Mahe", "Pondicherry", "Yanam"];
List<String> ladakh = ["Leh"];
List<String> defaultList = ["Please Select State First"];
List<List> districtList = [
  defaultList,
  rajsthan,
  gujrat,
  assam,
  bihar,
  goa,
  haryana,
  himachal,
  jammu,
  karnataka,
  kerala,
  mp,
  maharashtra,
  manipur,
  meghalaya,
  mizoram,
  nagaland,
  orissa,
  up,
  uk,
  punjab,
  sikkim,
  tamilnadu,
  tripura,
  westbengal,
  chhattisgarh,
  jharkhand,
  telangana,
  delhi,
  andaman,
  dadra,
  daman,
  pudu,
  ladakh
];
Map<String, int> statesID = {
  "rajsthan": 1,
  "gujrat": 2,
  "assam": 3,
  "bihar": 4,
  "goa": 5,
  "haryana": 6,
  "himachal": 7,
  "jammu": 8,
  "karnataka": 9,
  "kerala": 10,
  "mp": 11,
  "maharashtra": 12,
  "manipur": 13,
  "meghalay": 14,
  "mizoram": 15,
  "nagaland": 16,
  "orissa": 17,
  "up": 18,
  "uk": 19,
  "punjab": 20,
  "sikkim": 21,
  "tamilnadu": 22,
  "tripura": 23,
  "westbengal": 24,
  "chhattishgarh": 25,
  "jharkhand": 26,
  "telangana": 27,
  "delhi": 28,
  "andaman": 29,
  "dadra": 30,
  "daman": 31,
  "pudu": 32,
  "ladakh": 33
};

List<String> firstName = [];
List<bool> haveTravelled = [false, false, false, false, false];
List<bool> isDead = [false, false, false, false, false];
List<String> from = ["", "", "", "", ""];
List<String> to = ["", "", "", "", ""];
List<bool> isInfected = [false, false, false, false, false];
List<bool> haveSymptoms = [false, false, false, false, false];
List<bool> isCured = [false, false, false, false, false];
List<bool> hospitalised = [false, false, false, false, false];
List<String> ageGroup = ["", "", "", "", ""];
List<String> ageGroupList = [
  "0-10",
  "10-20",
  "20-30",
  "30-40",
  "40-50",
  "50-60",
  "60-70",
  "70+"
];
List<int> adhhar = [0, 0, 0, 0, 0];
List<String> country = ["", "", "", "", ""];
List<String> district = ["", "", "", "", ""];
List<String> fromDate = [];
List<String> toDate = [];
List<String> address = ["", "", "", "", ""];
List<String> state = [
  "Select State",
  "Select State",
  "Select State",
  "Select State",
  "Select State"
];
List<double> lat = [];
List<double> lng = [];
bool error = true;
List<Map<String, bool>> symptoms = [
  {
    "fever": false,
    "cough": false,
    "breathing": false,
    "nose": false,
    "dizziness": false,
    "pronounciation": false,
    "throatchest": false,
    "diarrhea": false,
    "attendJamat": false,
    "metJamatis": false,
    "metSomeoneAbroad": false,
    "outbreakPlaceVisit": false
  },
  {
    "fever": false,
    "cough": false,
    "breathing": false,
    "nose": false,
    "dizziness": false,
    "pronounciation": false,
    "throatchest": false,
    "diarrhea": false,
    "attendJamat": false,
    "metJamatis": false,
    "metSomeoneAbroad": false,
    "outbreakPlaceVisit": false
  },
  {
    "fever": false,
    "cough": false,
    "breathing": false,
    "nose": false,
    "dizziness": false,
    "pronounciation": false,
    "throatchest": false,
    "diarrhea": false,
    "attendJamat": false,
    "metJamatis": false,
    "metSomeoneAbroad": false,
    "outbreakPlaceVisit": false
  },
  {
    "fever": false,
    "cough": false,
    "breathing": false,
    "nose": false,
    "dizziness": false,
    "pronounciation": false,
    "throatchest": false,
    "diarrhea": false,
    "attendJamat": false,
    "metJamatis": false,
    "metSomeoneAbroad": false,
    "outbreakPlaceVisit": false
  },
  {
    "fever": false,
    "cough": false,
    "breathing": false,
    "nose": false,
    "dizziness": false,
    "pronounciation": false,
    "throatchest": false,
    "diarrhea": false,
    "attendJamat": false,
    "metJamatis": false,
    "metSomeoneAbroad": false,
    "outbreakPlaceVisit": false
  },
];
List<String> gender = ["", "", "", "", ""];
TextEditingController name1Editor = new TextEditingController();
TextEditingController name2Editor = new TextEditingController();
TextEditingController name3Editor = new TextEditingController();
TextEditingController name4Editor = new TextEditingController();
TextEditingController name5Editor = new TextEditingController();
TextEditingController name6Editor = new TextEditingController();
List<TextEditingController> editor = [
  name1Editor,
  name2Editor,
  name3Editor,
  name4Editor,
  name5Editor,
  name6Editor
];
TextEditingController a1Editor = new TextEditingController();
TextEditingController a2Editor = new TextEditingController();
TextEditingController a3Editor = new TextEditingController();
TextEditingController a4Editor = new TextEditingController();
TextEditingController a5Editor = new TextEditingController();
List<TextEditingController> adhharEditor = [
  a1Editor,
  a2Editor,
  a3Editor,
  a4Editor,
  a5Editor
];

TextEditingController add1Editor = new TextEditingController();
TextEditingController add2Editor = new TextEditingController();
TextEditingController add3Editor = new TextEditingController();
TextEditingController add4Editor = new TextEditingController();
TextEditingController add5Editor = new TextEditingController();
List<TextEditingController> addressEditor = [
  add1Editor,
  add2Editor,
  add3Editor,
  add4Editor,
  add5Editor
];

void makePost(
    int username,
    String name,
    String gender,
    String adhhar,
    bool infected,
    bool symptoms,
    bool cured,
    String district,
    String state,
    bool travel,
    String from,
    String to,
    String address,
    double lat,
    double lng) async {
  String url = "https://covid-mitrc.herokuapp.com/accounts/member/create";
  var body = {
    "user_id": username,
    "name": name,
    "father_name": "demo",
    "gender": gender,
    "aadhar": adhhar,
    "is_infected": infected,
    "diabetes": false,
    "symptoms": symptoms,
    "cured": cured,
    "travelled": travel,
    "state": district,
    "district": state,
    "address": address,
    "latitude": lat,
    "longitude": lng
  };
  print(body);
  //print(body);
  Response r = await post(
    Uri.parse(url),
    headers: {"Content-Type": "application/json"},
    body: json.encode(body),
  );
  print(r.body);
  print(r.statusCode);
  if (r.statusCode == 201) {
    error = false;
  } else {
    error = true;
  }
  //print(r.body);
}

Future<Map> geoCoding(String address) async {
  String url =
      "https://maps.googleapis.com/maps/api/geocode/json?address=$address&key=AIzaSyAu7bUrwnWzbfN2lK-zGxdf-KHbzvm-PNA";
  Response response = await http.get(url);
  return json.decode(response.body);
}