name: flutter_localization_master
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  rflutter_alert: ^1.0.2
  shared_preferences: ^0.5.6+2
  http: ^0.12.0+4
  simple_animations: ^1.3.3
  flutter_linkify:
  flutter_staggered_animations: "^0.1.2"
  flutter_spinkit: "^2.1.0"
  circular_reveal_animation: ^1.1.5
  fluttertoast: ^4.0.0
  translator: ^0.1.4
  flutter_rounded_date_picker: 1.0.0
  google_maps_flutter: ^0.5.11
  geolocator: ^5.3.0
  location_permissions: ^2.0.5
  youtube_api: ^0.7.2
  youtube_player: ^0.6.0
  flutube: 
  charts_flutter:
  url_launcher: ^5.4.2
  assets_audio_player: 
  shimmer:
  youtube_player_flutter: 
  carousel_slider: ^1.3.0
  audioplayers: ^0.14.1
  font_awesome_flutter: ^8.2.0
  toast:
  firebase_database:
  image_picker:
  mime:
  firebase_core:
  neumorphic: ^0.1.2
  video_player: ^0.10.1+3
  curved_navigation_bar:
  flutter_launcher_icons: "^0.7.3"
  google_nav_bar: ^2.0.0
  line_icons: ^0.2.0

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/logo/indcovid.png"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/lang/bn.json
    - lib/lang/en.json
    - lib/lang/gu.json
    - lib/lang/hi.json
    - lib/lang/kn.json
    - lib/lang/ml.json
    - lib/lang/mr.json
    - lib/lang/pa.json
    - lib/lang/ta.json
    - lib/lang/te.json
    - lib/lang/ur.json
    - assets/images/
    # - assets/audio/
    - assets/hindi.mp3
    - images/
    - assets/logo/
    - assets/
    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
